export const TRANSACCION_REPOSITORY = Symbol('TRANSACCION_REPOSITORY');
export const REGLA_ASOCIACION_REPOSITORY = Symbol('REGLA_ASOCIACION_REPOSITORY');
export const MOTOR_REGLAS_ASOCIACION = Symbol('MOTOR_REGLAS_ASOCIACION');
